export const HELLO_MESSAGE_SUCCESS = 'HELLO_MESSAGE_SUCCESS';
export const HELLO_MESSAGE_FAIL = 'HELLO_MESSAGE_FAIL';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
